### ISSUE TITLE
reg_average_interface

### ISSUE THREAD

**Issue by mmodat** [NifTK/nipype#16]
The reg_avarage needs modifying to deal with text file as input rather than direct command line arguments.

This is coming from the use of extremely long command lines that exceed the limit.

Basically, instead of being:
reg_average <arg1> <arg2> <arg3> ...
It has to be:
reg_average  --cmd_file <text_file>
where the text file contains "reg_average <arg1> <arg2> <arg3> ..."

**Comment by byvernault** [comment]
Request pushed. Closing issues.

**Comment by mmodat** [comment]
Been merged. Closed

**Comment by mmodat** [comment]
Erf. too fast

**Comment by mmodat** [comment]
:)
