### ISSUE TITLE
interfaces.niftyfit.dwi.DwiToolInputSpec b0_file, bvec_file shouldn't be mandatory

### ISSUE THREAD

**Issue by imalone** [NifTK/nipype#24]
These inputs are only required when the -syn option is used to create synthetic output. dwi_tool is mainly for getting parameters out from a model input (e.g. tensor file -> FA, MD), so it doesn't necessarily make sense to always require them. Ivor originally made generation of syn (the only output that needs them) conditional on supplying them.

**Comment by byvernault** [comment]
Only source_file is mandatory, right? what about mask_file and bval_file?

Or do you mean bval/bvec/b0 are required if syn set?

**Comment by imalone** [comment]
That's right, maybe I'm looking at a different branch to you, but they are all currently listed as mandatory in master, e.g. https://github.com/NifTK/nipype/blob/master/nipype/interfaces/niftyfit/dwi.py#L371

They are required if syn is set, but I think that can be left to the developer with a comment on the interface, since it's probably hard to change the trait based on a connection (could provide a separate interface for using the syn connection, but maybe overkill).

**Comment by byvernault** [comment]
I think we fixed this issue in the branch that will be pushed to Nipype.

**Comment by imalone** [comment]
Looks like still on in this one: https://github.com/NifTK/nipype/blob/push_to_upstream/nipype/interfaces/niftyfit/dwi.py#L371

**Comment by byvernault** [comment]
It's on mmodat fork to add niftyfit. I will edit this project as well soon.

**Comment by byvernault** [comment]
It should be good now. 

Reopen the issue if you think something else should be done.
Cheers,
